{
 "title": "SentinelStack - Logs Overview",
 "tags": [
  "sentinelstack",
  "devops",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Recent App Node Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\".+\"}"
    }
   ]
  },
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=~\".*backend.*\"}"
    }
   ]
  },
  {
   "title": "NGINX Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=~\".*nginx.*\"}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=~\".+\"} |= \"ERROR\""
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "sum(rate({job=~\".+\"}[5m]))"
    }
   ]
  }
 ]
}