{
 "title": "SentinelStack - Metrics Debug",
 "tags": [
  "sentinelstack",
  "devops",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Up Targets",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Available HTTP Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{__name__=~\"http_.*\"}"
    }
   ]
  },
  {
   "title": "Available Backend Custom Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{__name__=~\".*orders.*|.*checkout.*|.*backend.*\"}"
    }
   ]
  },
  {
   "title": "cAdvisor Metrics Check",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{__name__=~\"container_.*\"}"
    }
   ]
  },
  {
   "title": "Node Exporter Metrics Check",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{__name__=~\"node_.*\"}"
    }
   ]
  }
 ]
}